/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ComponentEngine: typeof import('./src/components/ComponentEngine.vue')['default']
    ComponentEventEditor: typeof import('./src/components/ComponentEventEditor.vue')['default']
    ComponentPropsEidtor: typeof import('./src/components/ComponentPropsEidtor.vue')['default']
    ComponentPropsSetting: typeof import('./src/components/ComponentPropsSetting.vue')['default']
    ComponentSheetsEditer: typeof import('./src/components/ComponentSheetsEditer.vue')['default']
    ComponentSheetsEditor: typeof import('./src/components/ComponentSheetsEditor.vue')['default']
    ComponentsMain: typeof import('./src/components/ComponentsMain.vue')['default']
    ComponentsModal: typeof import('./src/components/ComponentsModal.vue')['default']
    ComponentWrapper: typeof import('./src/components/ComponentWrapper.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    Icon: typeof import('./src/components/Icon.vue')['default']
    PropsSettingList: typeof import('./src/components/PropsSettingList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaModal: typeof import('./src/components/SchemaModal.vue')['default']
    SheetBackgroundEditer: typeof import('./src/components/SheetBackgroundEditer.vue')['default']
  }
}
