version: "3"
services: 
  nginx:
    container_name: webapp
    image: nginx
    restart: always
    ports:
      - 7091:7091
    volumes:
      - ./dist/:/html/gbf-portal-web/dist/
      - ./nginx/:/etc/nginx/conf.d/